name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          flake8 .
          black --check .

      - name: Testes unitários com cobertura
        run: |
          pytest -k "unit" --cov=app --cov=testes --cov-report=xml

      - name: Instalar Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable || sudo apt-get install -y chromium-browser

      - name: Testes E2E (headless)
        env:
          CHROME_BIN: /usr/bin/google-chrome
        run: |
          pytest -k "e2e" -vv -s
