name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Chrome (for Selenium headless)
        uses: browser-actions/setup-chrome@v1

      - name: Run only unit tests with coverage
        run: |
          pytest -k "unit" --cov=app --cov-report=xml --cov-report=term-missing -vv -s

      - name: Build HTML coverage report
        if: always()
        run: coverage html

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov-${{ github.run_id }}
          path: htmlcov/
          if-no-files-found: ignore
          retention-days: 7
